---
- name: Test multiline templated var with lookup()
  debug:
    msg: "{{ lookup('file', 'testfile.yml') }}"

- include_vars: file_included_from_role.yml
- name: Test multiline templated var with include_vars
  debug:
    msg: "{{ multilinevar_from_included_varfile }}"


